#!/usr/bin/env sh

# the scripting-addition must be loaded manually if you are running yabai on
# macOS Big Sur. Uncomment the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that it will be able to run the
# command without password

alias yc='yabai -m config'
alias yr='yabai -m rule --add' 
alias ys='yabai -m signal --add' 

sudo yabai --load-sa
ys event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yc layout                    bsp
yc mouse_follows_focus       off
yc focus_follows_mouse       off
yc window_border             off
yc window_placement          second_child
yc window_topmost            off
yc window_opacity            off
yc window_shadow             float
yc split_ratio               0.50
yc auto_balance              off
yc mouse_modifier            fn
yc mouse_action1             move
yc mouse_action2             resize

# padding settings
yc external_bar              all:28:0 
yc top_padding               4
yc bottom_padding            4
yc left_padding              4
yc right_padding             4
yc window_gap                4

# space-specific settings
# yc --space 1 layout          float

# rules
yr app=Firefox               space=1 # manage=off
yr app=Alacritty             space=2
yr app=iTerm                 space=2
yr app=Mail                  space=3
yr app=Spark                 space=3 
yr app=Telegram              space=3
yr app=Reeder                space=4
yr app=Finder                manage=off
yr app=MacPass               manage=off
yr app=Transmission          manage=off
yr app=Spotify               manage=off
yr app="System Preferences"  manage=off

# sketchybar events
ys event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
ys event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
