[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmake]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[line_break]
disabled = true

