#!/usr/bin/env bash

# Determine colors from base16-shell
# BG=$(sed -n -e 's:^color_background="\(..\)/\(..\)/\(..\)".*:0xff\1\2\3:p' ~/.base16_theme)
# FG=$(sed -n -e 's:^color_foreground="\(..\)/\(..\)/\(..\)".*:0xff\1\2\3:p' ~/.base16_theme)
BG=$(sed -n -e 's:^color_background="\(..\)/\(..\)/\(..\)".*:0xff\1\2\3:p' ~/.config/base16-project/base16_shell_theme)
FG=$(sed -n -e 's:^color_foreground="\(..\)/\(..\)/\(..\)".*:0xff\1\2\3:p' ~/.config/base16-project/base16_shell_theme)

PLUGINS="$HOME/.config/sketchybar/plugins"

# Bar
sketchybar --bar     \
  position=top       \
  height=35          \
  margin=4           \
  y_offset=-35       \
  corner_radius=10   \
  border_width=0     \
  border_color=$BG   \
  blur_radius=0      \
  padding_left=16    \
  padding_right=16   \
  color=$BG          \
  display=all        \
  hidden=off         \
  topmost=off        \
  font_smoothing=off \
  shadow=off

# Global defaults
sketchybar --default \
  updates=when_shown \
  drawing=on         \
  cache_scripts=on                      

# Label Defaults
sketchybar --default                       \
  label.font="Iosevka Nerd Font:Bold:14.0" \
  label.color=$FG                          \
  label.highlight_color=$FG                \
  label.padding_left=4                     \
  label.padding_right=4                    \
  label.y_offset=-2

# Icon Defaults
sketchybar --default                      \
  icon.font="Iosevka Nerd Font:Bold:14.0" \                       

# Background Defaults
sketchybar --default          \
  background.height=32        \
  background.border_color=$BG \
  background.border_width=0   \
  background.corner_radius=0  \
  background.color=$BG        \
  background.drawing=off                                       

# Spaces
sketchybar --default                        \
  icon.padding_left=4                       \
  icon.padding_right=4                      \
  icon.y_offset=-2                          \
  --add space one left                      \
  --set one associated_display=1            \
    associated_space=1                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 1" \
  --add space two left                      \
  --set two associated_display=1            \
    associated_space=2                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 2" \
  --add space three left                    \
  --set three associated_display=1          \
    associated_space=3                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 3" \
  --add space four left                     \
  --set four associated_display=1           \
    associated_space=4                      \
    icon=                                  \
    icon.highlight_color=0xff88c0d0         \
    click_script="yabai -m space --focus 4"

# Right Items
sketchybar --default             \
  label.padding_left=0           \
  label.padding_right=0          \
  icon.padding_left=20           \
  icon.padding_right=8           \
  icon.y_offset=-2               \
  --add item clock right         \
  --set clock                    \
    update_freq=10               \
    script="$PLUGINS/clock.sh"   \
    icon=                       \
    icon.y_offset=-2             \
    icon.color=0xff8fbcbb        \
  --add item date right          \
  --set date                     \
    update_freq=100              \
    script="$PLUGINS/date.sh"    \
    icon=                       \
    icon.y_offset=-2             \
    icon.color=0xffb48ead        \
  --add item battery right       \
  --set battery                  \
    update_freq=3                \
    script="$PLUGINS/power.sh"   \
    icon=                       \
    icon.color=0xffbf616a        \
  --add item sound right         \
  --set sound                    \
    update_freq=5                \
    icon.color=0xff5e81ac        \
    script="$PLUGINS/sound.sh"   \
  --add item weather right       \
  --set weather                  \
    update_freq=1800             \
    icon.color=0xffebcb8b        \
    script="$PLUGINS/weather.sh" \
  --add item wifi right          \
  --set wifi                     \
    script="$PLUGINS/wifi.sh"    \
    update_freq=5                \
  --add item mailIndicator right \
  --set mailIndicator            \
    update_freq=30               \
    icon.color=0xff5e81ac        \
    script="$PLUGINS/mail.sh"    \
    click_script="osascript -e 'tell application \"Mail\" to activate'" 

# Center Items
sketchybar --add event window_focus \
              --add event title_change

sketchybar --add item title left                          \
              --set title script="$PLUGINS/window_title.sh" \
              --subscribe                                   \
                title window_focus front_app_switched space_change title_change

# Animate bar startup
sketchybar --animate tanh 30 --bar y_offset=-7

sketchybar --update && echo "sketchybar configuration loaded.."
