#!/usr/bin/env sh

alias config='spacebar -m config'

# General
config position               top
config background_color       0xff1a1b26
config foreground_color       0xffa8a8a8
config text_font              "Iosevka Nerd Font:Medium:13.0"
config icon_font              "Iosevka Nerd Font:Medium:13.0"
config height                 28
config padding_left           15 
config padding_right          15
config spacing_left           15
config spacing_right          25

# Widgets
config spaces                 on
config space_icon             
config space_icon_color       0xff458588

config title                  on

config right_shell            on
config right_shell_icon       
config right_shell_icon_color 0xffd08770
config right_shell_command    "curl -s 'wttr.in/Orlando?format=%t' | cut -c 2-"

config power                  on
config power_icon_strip        
config battery_icon_color     0xffbf616a
config power_icon_color       0xffebcb8b

config clock                  on
config clock_format           "%a %-m/%-d %-I:%M %p"
config clock_icon             
config clock_icon_color       0xffb48ead

config dnd                    on
config dnd_icon               
config dnd_icon_color         0xffb48ead

echo "spacebar configuration loaded.."
