live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Oblique"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 10
y = 10
